SELECT COUNT(*) AS TIMESORDERED, P.PRODUCTDESCRIPTION
FROM ORDERLINE_T OL JOIN
PRODUCT_T P ON OL.PRODUCTID=P.PRODUCTID
WHERE OL.ORDEREDQUANTITY > 0 
GROUP BY P.PRODUCTDESCRIPTION
ORDER BY TIMESORDERED DESC
