SELECT COUNT(E.EMPLOYEESUPERVISOR) AS HeadCount,
    S.EMPLOYEENAME AS SUPERVISER
   FROM EMPLOYEE_T E, EMPLOYEE_T S
   WHERE E.EMPLOYEESUPERVISOR = S.EMPLOYEEID
   GROUP BY S.EMPLOYEENAME
   HAVING COUNT(*) > 2
